name: Generate 3D World TIFF

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual triggers from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Processing
      run: |
        sudo apt update
        sudo apt install -y default-jre  # Install Java Runtime
        wget https://github.com/processing/processing4/releases/download/processing-1288-4.0b8/processing-4.0b8-linux-x64.tgz
        tar -xzf processing-4.0b8-linux-x64.tgz
        sudo ln -s $PWD/processing-4.0b8/processing-java /usr/local/bin/processing-java

    - name: Run Processing sketch
      run: |
        processing-java --sketch=$PWD --output=$PWD/output --force --run

    - name: Upload generated TIFF
      uses: actions/upload-artifact@v4
      with:
        name: output-tif
        path: output/output.tif  # Path to the generated TIFF
