name: Generate 3D World TIFF

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 to avoid deprecated Node.js version

    - name: Install Processing
      run: |
        sudo apt update
        sudo apt install -y default-jre  # Install Java Runtime
        wget https://github.com/benfry/processing4/releases/download/processing-1293-4.3/processing-4.3-linux-x64.tgz  # Correct URL
        tar -xzf processing-4.3-linux-x64.tgz  # Correct file name
        sudo ln -s $PWD/processing-4.3/processing-java /usr/local/bin/processing-java  # Updated directory

    - name: Prepare sketch directory
      run: |
        mkdir sketch_folder   # Create a new directory for the sketch
        mv sketch_3d_world_render.pde sketch_folder/sketch_folder.pde  # Move and rename the .pde file

    - name: Run Processing sketch
      run: |
        processing-java --sketch=$PWD/sketch_folder --output=$PWD/output --force --run

    - name: List output directory
      run: ls -al $PWD/output  # List the contents of the output directory to verify

    - name: List output directory
      run: ls -al $PWD/sketch_folder  # List the contents of the output directory to verify

    - name: List output directory
      run: ls -al $PWD  # List the contents of the output directory to verify

    - name: Upload generated TIFF
      if: success()  # Only upload if previous steps were successful
      uses: actions/upload-artifact@v4
      with:
        name: output-tif
        path: output/output.tif  # Path to the generated TIFF
